# Generated by Django 5.1.2 on 2026-09-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('holder_name', models.CharField(max_length=150)),
                ('record_type', models.CharField(choices=[('certificate', 'Training certificate'), ('internship', 'Internship completion'), ('project', 'Project delivery')], default='certificate', max_length=20)),
                ('issued_on', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-issued_on'],
            },
        ),
    ]
