# Generated by Django 4.2.21 on 2026-09-09 20:27

from django.db import migrations, models
from django.utils.text import slugify


def backfill_case_study_slugs(apps, schema_editor):
    CaseStudy = apps.get_model('core', 'CaseStudy')
    seen = set()
    for cs in CaseStudy.objects.all():
        base = slugify(cs.title)[:220] or f'case-study-{cs.pk}'
        slug = base
        n = 2
        while slug in seen or CaseStudy.objects.filter(slug=slug).exclude(pk=cs.pk).exists():
            suffix = f'-{n}'
            slug = f'{base[:220 - len(suffix)]}{suffix}'
            n += 1
        seen.add(slug)
        cs.slug = slug
        cs.save(update_fields=['slug'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_casestudy_faq_industry_processstep_techstackitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='content',
            field=models.TextField(blank=True, help_text='Full case study body, shown on its detail page.'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=False, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_case_study_slugs, noop),
        migrations.AlterField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='logo_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='techstackitem',
            name='logo_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
